backend: chroma
backends:
  chroma:
    config:
      collection_name: test_memories
      embedding_model: sentence-transformers/all-MiniLM-L6-v2
      persistent: true
      similarity_threshold: 0.5
    enabled: true
  in_memory:
    config:
      capacity: 1000
      persistent: false
    enabled: false
